version: '2'
services:

  core:
    restart: always
    container_name: dmoney-core
    build: docker/core
    image: crypto/core
    ports:
      - "11625:11625"
    env_file:
      - .env
      - .core-cfg
    links:
      - postgresstlr
    depends_on:
      - postgresstlr
    environment:
      PGUSER: "${POSTGRES_USER_ST}"
      PGPASSWORD: "${POSTGRES_PASSWORD_ST}"
      PGHOST: postgresstlr
    networks:
      guroshnet:
        external: true
          ipv4_address: 188.0.0.9

  fee:
    restart: always
    container_name: dmoney-fee
    build: docker/core
    image: crypto/fee
    ports:
      - "11635:11635"
    env_file:
      - .env
      - .core1-cfg
    links:
      - postgresstlr
    depends_on:
      - postgresstlr
    environment:
      PGUSER: "${POSTGRES_USER_ST}"
      PGPASSWORD: "${POSTGRES_PASSWORD_ST}"
      PGHOST: postgresstlr    
    networks:
      guroshnet:
        external: true
          ipv4_address: 188.0.0.10

  validator:
    restart: always
    container_name: dmoney-validator
    build: docker/core
    image: crypto/validator
    ports:
      - "11645:11645"
    env_file:
      - .env
      - .core2-cfg
    links:
      - postgresstlr
    depends_on:
      - postgresstlr
    environment:
      PGUSER: "${POSTGRES_USER_ST}"
      PGPASSWORD: "${POSTGRES_PASSWORD_ST}"
      PGHOST: postgresstlr
    networks:
      guroshnet:
        external: true
          ipv4_address: 188.0.0.11

  horizon: 
    restart: always
    container_name: dmoney-horizon
    build: docker/horizon
    image: crypto/horizon
    ports:
      - "8000:8000"
    links:
      - postgresstlr
      - redis
      - core
    depends_on:
      - postgresstlr
    env_file:
      - .core-cfg
      - .hz-cfg
    environment:
      DATABASE_URL: "postgresstlr://${POSTGRES_USER_ST}:${POSTGRES_PASSWORD_ST}@postgresstlr/horizon?sslmode=disable"
      STELLAR_CORE_DATABASE_URL: "postgresstlr://${POSTGRES_USER_ST}:${POSTGRES_PASSWORD_ST}@postgresstlr/stellarcore?sslmode=disable"
      NETWORK_PASSPHRASE: ${NETWORK_PASSPHRASE}
      STELLAR_CORE_URL: "http://core:11626"
      REDIS_URL: "redis://redis:6379"
      LOG_LEVEL: "info"
      INGEST: "true"
    networks:
      guroshnet:
        external: true
          ipv4_address: 188.0.0.12

  postgresstlr:
    restart: always
    container_name: dmoney-postgres
    build: docker/postgres
    image: crypto/postgres
    ports:
      - "5433:5432"
    volumes:
      - storage:/var/lib/postgresql/data
    environment:
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_ST}"
      POSTGRES_USER: "${POSTGRES_USER_ST}" 
    networks:
      guroshnet:
        external: true
          ipv4_address: 188.0.0.13

  redis:
    restart: always
    container_name: dmoney-redis
    image: redis:3.2
    networks:
      guroshnet:
        external: true

volumes:
  storage: 
